on:
  pull_request:
    branches: [main]

name: Run Tests

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ~/ChumsApp
          submodules: 'true'

      - name: Checkout Tests
        uses: actions/checkout@v2
        with:
          repository: pranavmalvawala/ChumsTests
          path: ~/ChumsTests

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
    
      - name: Install Dependencies
        working-directory: ~/ChumsApp
        run: npm install

      - name: ChumsApp - Copy .env
        working-directory: ~/ChumsApp
        run: cp dotenv.sample.txt .env
  
      - name: Cypress run with env
        uses: cypress-io/github-action@v2
        with:
          working-directory: ~/ChumsTests
          start: |
            cd ~/ChumsApp
            npm start
          wait-on: 'http://localhost:3101'
          spec: cypress/integration/*.spec.js
          record: true
        env:
          CYPRESS_ACCESS_API: 'https://accessapi.staging.churchapps.org'
          CYPRESS_ATTENDANCE_API: 'https://attendanceapi.staging.churchapps.org'
          CYPRESS_GIVING_API: 'https://givingapi.staging.churchapps.org'
          CYPRESS_MEMBERSHIP_API: 'https://membershipapi.staging.churchapps.org'
          CYPRESS_RECORD_KEY: 'c08234a0-1251-49a5-ab69-a85f8cda73e0'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}